version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=liyi
      - MYSQL_DATABASE=oscar_mcmaster
      - MYSQL_USER=oscar
      - MYSQL_PASSWORD=oscar
    networks:
      - overlay
    volumes:
      - ./dbdump/oscarON.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./oscar/database/mysql/updates:/docker-entrypoint-initdb.d
  tomcat_oscar:
    image: oscar:15
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - overlay
    depends_on:
      - db
    ports:
      - 8080:8080

networks:
  overlay:
