version: '3'

services:
  db:
    image: mariadb:10
    build:
      context: .
      dockerfile: Dockerfile-mysql
    networks:
      - overlay

  tomcat_oscar:
    image: oscar:15
    build:
      context: .
      dockerfile: Dockerfile-oscar
    networks:
      - overlay
    depends_on:
      - db
    ports:
      - 8080:8080

networks:
  overlay:
